main : RLNNCognitiveEngineTester_v2.cpp
	g++ -o RLNNCognitiveEngineTester_v2 RLNNCognitiveEngineTester_v2.cpp -std=gnu++11  -larmadillo -lmlpack -lboost_serialization -lboost_system -pthread -O2 2> err.txt


